mstrSQL = ""
mstrSQL = "SELECT case when exists (select * from SNDeliveryJob with (nolock) where OrderID = " & clngObjectKey & ") then IsOrderInd else 0 end as IsOrderInd FROM SNOrder with (nolock) WHERE OrderID = " & clngObjectKey
Set mRS = mobjDBServer.DoQuery(CStr(evDBConnString), CStr(mstrSQL))
If mRS("IsOrderInd") = -1 Then
    mstrSQL = ""
    mstrSQL = mstrSQL & " SELECT '<OJ index=''' + CAST(ROW_NUMBER() OVER(ORDER BY DJ.DeliveryJobCount) as nvarchar) + '''>'"
    mstrSQL = mstrSQL & " + '<OJ.NUMBER>' + cast(DJ.OrderID as nvarchar) + '-' + cast(DJ.DeliveryJobCount as nvarchar) + '</OJ.NUMBER>'"
    mstrSQL = mstrSQL & " + '<OJ.COUNT>' + cast(DJ.DeliveryJobCount as nvarchar) + '</OJ.COUNT>'"
    mstrSQL = mstrSQL & " + '<OJ.CUSTOMERNBR>' + dbo.fn_FormatXMLChars(ISNULL(CU.OMDCustomerNbr,isnull(BCU.OMDCustomerNbr,'')))  + '</OJ.CUSTOMERNBR>'"
    mstrSQL = mstrSQL & " + '<OJ.COMPANYNAME>' + dbo.fn_FormatXMLChars(ISNULL(DJ.CustomerName,''))  + '</OJ.COMPANYNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSLABEL>' + dbo.fn_FormatXMLChars(cast(ISNULL(DJ.AddressLabel,'') as nvarchar(max)))  + '</OJ.ADDRESSLABEL>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESS1>' + dbo.fn_FormatXMLChars(ISNULL(LO.Address1,''))  + '</OJ.ADDRESS1>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESS2>' + dbo.fn_FormatXMLChars(ISNULL(LO.Address2,''))  + '</OJ.ADDRESS2>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSCITY>' + dbo.fn_FormatXMLChars(ISNULL(LO.City,''))  + '</OJ.ADDRESSCITY>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSSTATE>' + dbo.fn_FormatXMLChars(ISNULL(LO.StateCode,''))  + '</OJ.ADDRESSSTATE>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSPOSTALCODE>' + dbo.fn_FormatXMLChars(ISNULL(LO.PostalCode,''))  + '</OJ.ADDRESSPOSTALCODE>' "
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSONELINE>' + dbo.fn_FormatXMLChars(case when len(LO.City) > 0 then LO.Address1 + case when LEN(LO.Address2) > 0 then ' ' + LO.Address2 else '' end  + ', ' +  LO.City + ', ' + LO.StateCode + ' ' + LO.PostalCode else '' end) + '</OJ.ADDRESSONELINE>' "
    mstrSQL = mstrSQL & " + '<OJ.PRIMARYCONTACTNAME>' + dbo.fn_FormatXMLChars(isnull(case when DJ.PriContactSelect = -101 then OD.BillingContactName else DJ.PriContactName end,'')) + '</OJ.PRIMARYCONTACTNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.PRIMARYCONTACTTITLE>' + dbo.fn_FormatXMLChars(isnull(case when DJ.PriContactSelect = -101 then case when OD.BillToContactSelect > 0 then (SELECT Title FROM SNContact with (nolock) WHERE ContactID = OD.BillToContactSelect) else '' end else PC.Title end,'')) + '</OJ.PRIMARYCONTACTTITLE>'"
    mstrSQL = mstrSQL & " + '<OJ.PRIMARYPHONE>' + dbo.fn_FormatPhoneNumber(case when DJ.PriContactSelect = -101 then OD.BillingContactPhoneNbr else DJ.PriContactPhone end) + case when DJ.PriContactSelect = -101 then case when isnull(OD.BillingContactPhoneExt,'') <> '' then 'x' + isnull(OD.BillingContactPhoneExt,'') else '' end else case when isnull(DJ.PriContactPhoneExt,'') <> '' then 'x' + isnull(DJ.PriContactPhoneExt,'') else '' end end + '</OJ.PRIMARYPHONE>'"
    mstrSQL = mstrSQL & " + '<OJ.PRICONTACTFAX>' + dbo.fn_FormatPhoneNumber(case when DJ.PriContactSelect = -101 then OD.BillingContactFaxNbr else DJ.PriContactFax end) + '</OJ.PRICONTACTFAX>'"
    mstrSQL = mstrSQL & " + '<OJ.PRICONTACTCELL>' + dbo.fn_FormatPhoneNumber(case when DJ.PriContactSelect = -101 then OD.BillingContactCellNbr else DJ.PriContactCell end) + '</OJ.PRICONTACTCELL>'"
    mstrSQL = mstrSQL & " + '<OJ.PRICONTACTEMAIL>' + dbo.fn_FormatXMLChars(isnull(case when DJ.PriContactSelect = -101 then OD.BillingContactEmailAddr else DJ.PriContactEmail end,'')) + '</OJ.PRICONTACTEMAIL>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTNAME>' + dbo.fn_FormatXMLChars(isnull(case when DJ.ITContactSelect = -101 then OD.BillingContactName else DJ.ITContactName end,'')) + '</OJ.ITCONTACTNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTTITLE>' + dbo.fn_FormatXMLChars(isnull(case when DJ.ITContactSelect = -101 then case when OD.BillToContactSelect > 0 then (SELECT Title FROM SNContact with (nolock) WHERE ContactID = OD.BillToContactSelect) else '' end else IC.Title end,'')) + '</OJ.ITCONTACTTITLE>'"
    mstrSQL = mstrSQL & " + '<OJ.ITPHONE>' + dbo.fn_FormatPhoneNumber(case when DJ.ITContactSelect = -101 then OD.BillingContactPhoneNbr else DJ.ITContactPhone end) + case when DJ.ITContactSelect = -101 then case when isnull(OD.BillingContactPhoneExt,'') <> '' then 'x' + isnull(OD.BillingContactPhoneExt,'') else '' end else case when isnull(DJ.ITContactPhoneExt,'') <> '' then 'x' + isnull(DJ.ITContactPhoneExt,'') else '' end end + '</OJ.ITPHONE>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTFAX>' + dbo.fn_FormatPhoneNumber(case when DJ.ITContactSelect = -101 then OD.BillingContactFaxNbr else DJ.ITContactFax end) + '</OJ.ITCONTACTFAX>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTCELL>' + dbo.fn_FormatPhoneNumber(case when DJ.ITContactSelect = -101 then OD.BillingContactCellNbr else DJ.ITContactCell end) + '</OJ.ITCONTACTCELL>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTEMAIL>' + dbo.fn_FormatXMLChars(isnull(case when DJ.ITContactSelect = -101 then OD.BillingContactEmailAddr else DJ.ITContactEmail end,'')) + '</OJ.ITCONTACTEMAIL>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTNAME>' + dbo.fn_FormatXMLChars(isnull(case when DJ.MeterContactSelect = -101 then OD.BillingContactName else (SELECT isnull(FirstName,'') FROM SNPerson with (nolock) WHERE PersonID = MC.PersonID) + ' ' + (SELECT isnull(LastName,'') FROM SNPerson with (nolock) WHERE PersonID = MC.PersonID) end,'')) + '</OJ.METERCONTACTNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTTITLE>' + dbo.fn_FormatXMLChars(isnull(case when DJ.MeterContactSelect = -101 then case when OD.BillToContactSelect > 0 then (SELECT Title FROM SNContact with (nolock) WHERE ContactID = OD.BillToContactSelect) else '' end else MC.Title end,'')) + '</OJ.METERCONTACTTITLE>'"
    mstrSQL = mstrSQL & " + '<OJ.METERPHONE>' + dbo.fn_FormatPhoneNumber(case when DJ.MeterContactSelect = -101 then OD.BillingContactPhoneNbr else MC.RPTOfficePhone end) + case when DJ.MeterContactSelect = -101 then case when isnull(OD.BillingContactPhoneExt,'') <> '' then 'x' + isnull(OD.BillingContactPhoneExt,'') else '' end else case when isnull(MC.RPTOfficePhoneExt,'') <> '' then 'x' + isnull(MC.RPTOfficePhoneExt,'') else '' end end + '</OJ.METERPHONE>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTFAX>' + dbo.fn_FormatPhoneNumber(case when DJ.MeterContactSelect = -101 then OD.BillingContactFaxNbr else MC.RPTFaxPhone end) + '</OJ.METERCONTACTFAX>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTCELL>' + dbo.fn_FormatPhoneNumber(case when DJ.MeterContactSelect = -101 then OD.BillingContactCellNbr else MC.RPTCellPhone end) + '</OJ.METERCONTACTCELL>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTEMAIL>' + dbo.fn_FormatXMLChars(isnull(case when DJ.MEterContactSelect = -101 then OD.BillingContactEmailAddr else MC.RPTEmailAddress end,'')) + '</OJ.METERCONTACTEMAIL>'"
    mstrSQL = mstrSQL & " + '</OJ>'"
    mstrSQL = mstrSQL & " FROM SNDeliveryJob as DJ with (nolock)"
    mstrSQL = mstrSQL & " JOIN SNOrder as OD with (nolock) on OD.OrderID = DJ.OrderID"
    mstrSQL = mstrSQL & " LEFT JOIN SNCustomer as CU with (nolock) on CU.CustomerID = DJ.CustomerSelect"
    mstrSQL = mstrSQL & " LEFT JOIN SNCustomer as BCU with (nolock) on BCU.CustomerID = OD.BillToAccountSelect"
    mstrSQL = mstrSQL & " LEFT JOIN SNEntityLocation as EL with (nolock) on EL.EntityID = DJ.EntityID AND EL.LocationTypeID = (SELECT LocationTypeID FROM SNLocationType with (nolock) WHERE SystemLabel = 'Company.Address')"
    mstrSQL = mstrSQL & " LEFT JOIN SNLocation as LO with (nolock) on LO.LocationID = EL.LocationID"
    mstrSQL = mstrSQL & " LEFT JOIN SNContact as PC with (nolock) on PC.ContactID = DJ.PriContactSelect"
    mstrSQL = mstrSQL & " LEFT JOIN SNContact as IC with (nolock) on IC.ContactID = DJ.ITContactSelect"
    mstrSQL = mstrSQL & " LEFT JOIN SNContact as MC with (nolock) on MC.ContactID = DJ.MeterContactSelect"
    mstrSQL = mstrSQL & " Where DJ.OrderID = " & clngObjectKey
Else
    mstrSQL = ""
    mstrSQL = mstrSQL & " SELECT '<OJ index=''' + CAST(ROW_NUMBER() OVER(ORDER BY OD.OrderID) as nvarchar) + '''>'"
    mstrSQL = mstrSQL & " + '<OJ.NUMBER>' + cast(OD.OrderID as nvarchar) + '-1' + '</OJ.NUMBER>'"
    mstrSQL = mstrSQL & " + '<OJ.COUNT>1</OJ.COUNT>'"
    mstrSQL = mstrSQL & " + '<OJ.CUSTOMERNBR>' + dbo.fn_FormatXMLChars(ISNULL(CU.OMDCustomerNbr,'')) + '</OJ.CUSTOMERNBR>'"
    mstrSQL = mstrSQL & " + '<OJ.COMPANYNAME>' + dbo.fn_FormatXMLChars(isnull(OD.BillingCustomerName ,'')) + '</OJ.COMPANYNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSLABEL>' + dbo.fn_FormatXMLChars(case when len(OD.BillingCity) > 0 then OD.BillingAddress1 + case when LEN(OD.BillingAddress2) > 0 then CHAR(13) + CHAR(10) + OD.BillingAddress2 else '' end  + CHAR(13) + CHAR(10) + OD.BillingCity + ', ' + OD.BillingState + ' ' + OD.BillingPostalCode else '' end)  + '</OJ.ADDRESSLABEL>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESS1>' + dbo.fn_FormatXMLChars(isnull(OD.BillingAddress1 ,'')) + '</OJ.ADDRESS1>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESS2>' + dbo.fn_FormatXMLChars(isnull(OD.BillingAddress2 ,'')) + '</OJ.ADDRESS2>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSCITY>' + dbo.fn_FormatXMLChars(isnull(OD.BillingCity ,'')) + '</OJ.ADDRESSCITY>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSSTATE>' + dbo.fn_FormatXMLChars(isnull(OD.BillingState ,'')) + '</OJ.ADDRESSSTATE>'"
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSPOSTALCODE>' + dbo.fn_FormatXMLChars(isnull(OD.BillingPostalCode ,'')) + '</OJ.ADDRESSPOSTALCODE>' "
    mstrSQL = mstrSQL & " + '<OJ.ADDRESSONELINE>' + dbo.fn_FormatXMLChars(case when len(OD.BillingCity) > 0 then OD.BillingAddress1 + case when LEN(OD.BillingAddress2) > 0 then ' ' + OD.BillingAddress2 else '' end  + ', ' +  OD.BillingCity + ', ' + OD.BillingState + ' ' + OD.BillingPostalCode else '' end) + '</OJ.ADDRESSONELINE>' "
    mstrSQL = mstrSQL & " + '<OJ.PRIMARYCONTACTNAME>' + dbo.fn_FormatXMLChars(isnull(OD.BillingContactName ,'')) + '</OJ.PRIMARYCONTACTNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.PRIMARYCONTACTTITLE>' + dbo.fn_FormatXMLChars(isnull(case when OD.BillToContactSelect > 0 then (SELECT Title FROM SNContact with (nolock) WHERE ContactID = OD.BillToContactSelect) else '' end,'')) + '</OJ.PRIMARYCONTACTTITLE>'"
    mstrSQL = mstrSQL & " + '<OJ.PRIMARYPHONE>' + dbo.fn_FormatPhoneNumber(OD.BillingContactPhoneNbr) + case when isnull(OD.BillingContactPhoneExt,'') <> '' then 'x' + isnull(OD.BillingContactPhoneExt,'') else '' end + '</OJ.PRIMARYPHONE>'"
    mstrSQL = mstrSQL & " + '<OJ.PRICONTACTFAX>' + dbo.fn_FormatPhoneNumber(OD.BillingContactFaxNbr) + '</OJ.PRICONTACTFAX>'"
    mstrSQL = mstrSQL & " + '<OJ.PRICONTACTCELL>' + dbo.fn_FormatPhoneNumber(OD.BillingContactCellNbr) + '</OJ.PRICONTACTCELL>'"
    mstrSQL = mstrSQL & " + '<OJ.PRICONTACTEMAIL>' + dbo.fn_FormatXMLChars(isnull(OD.BillingContactEmailAddr ,'')) + '</OJ.PRICONTACTEMAIL>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTNAME>' + dbo.fn_FormatXMLChars(isnull(OD.BillingContactName ,'')) + '</OJ.ITCONTACTNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTTITLE>' + dbo.fn_FormatXMLChars(isnull(case when OD.BillToContactSelect > 0 then (SELECT Title FROM SNContact with (nolock) WHERE ContactID = OD.BillToContactSelect) else '' end,'')) + '</OJ.ITCONTACTTITLE>'"
    mstrSQL = mstrSQL & " + '<OJ.ITPHONE>' + dbo.fn_FormatPhoneNumber(OD.BillingContactPhoneNbr) + case when isnull(OD.BillingContactPhoneExt,'') <> '' then 'x' + isnull(OD.BillingContactPhoneExt,'') else '' end + '</OJ.ITPHONE>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTFAX>' + dbo.fn_FormatPhoneNumber(OD.BillingContactFaxNbr) + '</OJ.ITCONTACTFAX>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTCELL>' + dbo.fn_FormatPhoneNumber(OD.BillingContactCellNbr) + '</OJ.ITCONTACTCELL>'"
    mstrSQL = mstrSQL & " + '<OJ.ITCONTACTEMAIL>' + dbo.fn_FormatXMLChars(isnull(OD.BillingContactEmailAddr ,'')) + '</OJ.ITCONTACTEMAIL>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTNAME>' + dbo.fn_FormatXMLChars(isnull(OD.BillingContactName ,'')) + '</OJ.METERCONTACTNAME>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTTITLE>' + dbo.fn_FormatXMLChars(isnull(case when OD.BillToContactSelect > 0 then (SELECT Title FROM SNContact with (nolock) WHERE ContactID = OD.BillToContactSelect) else '' end,'')) + '</OJ.METERCONTACTTITLE>'"
    mstrSQL = mstrSQL & " + '<OJ.METERPHONE>' + dbo.fn_FormatPhoneNumber(OD.BillingContactPhoneNbr) + case when isnull(OD.BillingContactPhoneExt,'') <> '' then 'x' + isnull(OD.BillingContactPhoneExt,'') else '' end + '</OJ.METERPHONE>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTFAX>' + dbo.fn_FormatPhoneNumber(OD.BillingContactFaxNbr) + '</OJ.METERCONTACTFAX>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTCELL>' + dbo.fn_FormatPhoneNumber(OD.BillingContactCellNbr) + '</OJ.METERCONTACTCELL>'"
    mstrSQL = mstrSQL & " + '<OJ.METERCONTACTEMAIL>' + dbo.fn_FormatXMLChars(isnull(OD.BillingContactEmailAddr ,'')) + '</OJ.METERCONTACTEMAIL>'"
    mstrSQL = mstrSQL & " + '</OJ>'"
    mstrSQL = mstrSQL & " FROM SNOrder as OD with (nolock) "
    mstrSQL = mstrSQL & " LEFT JOIN SNCustomer as CU with (nolock) on CU.CustomerID = OD.BillToAccountSelect"
    mstrSQL = mstrSQL & " Where OD.OrderID = " & clngObjectKey