  If Len(mstrXML) = 0 Then
              
              If mstrCatalogServer = "" Then
                mstrSQL = ""
                mstrSQL = "SELECT isnull(MasterCatalogServer,'') MasterCatalogServer FROM SCMaster.dbo.SNMasterSysParm with (nolock)"
                Set mRS = mobjDBServer.DoQuery(CStr(evDBConnString), CStr(mstrSQL))
                mstrCatalogServer = CStr(mRS("MasterCatalogServer"))
                Set mRS = Nothing
              End If
              
              mstrSQL = ""
              mstrSQL = "SELECT isnull(stuff((select ',[PRICELEVEL' + cast(PriceLevelID as nvarchar) + ']' from SNPriceLevel with (nolock) where isnull(IsStandardInd,0) = 0 for xml path('')),1,1,''),'') col"
              mstrSQL = mstrSQL & "     , isnull(replace(replace(stuff((select ' + ''<OL.PRICELEVEL' + cast(PriceLevelID as nvarchar) + '>'' + case when PRICELEVEL' + cast(PriceLevelID as nvarchar) + ' >= 0 then dbo.fn_FormatCurrency(PRICELEVEL' + cast(PriceLevelID as nvarchar) + ') else '''' end + ''</OL.PRICELEVEL' + cast(PriceLevelID as nvarchar) + '>''' from SNPriceLevel with (nolock) where isnull(IsStandardInd,0) = 0 for xml path('')),1,1,''),'&lt;','<'),'&gt;','>'),'') val"
              Set mRS = mobjDBServer.DoQuery(CStr(evDBConnString), CStr(mstrSQL))
              
              mstrSQL = ""
              mstrSQL = mstrSQL & " SELECT  '<OL index=''' + CAST(ROW_NUMBER() OVER(ORDER BY OL.SeqNbr) as nvarchar) + '''>' + "
              mstrSQL = mstrSQL & "        + '<OL.BUYLINETOTAL>' + case when OL.BuyPrice = 0 or OL.Quantity = 0 then '' else dbo.fn_FormatCurrency(OL.BuyPrice * OL.Quantity) end + '</OL.BUYLINETOTAL>'"
              mstrSQL = mstrSQL & "        + '<OL.BUYUNITPRICE>' + dbo.fn_FormatCurrency(OL.BuyPrice) + '</OL.BUYUNITPRICE>'"
              mstrSQL = mstrSQL & "        + '<OL.BUYUNITPRICEPCT>' + case when isnull(OL.CSMPPCTEntryPCT,0) = 0 then dbo.fn_FormatCurrency(OL.BuyPrice) else dbo.fn_FormatCurrency(OL.DealerCostAmt) end + '</OL.BUYUNITPRICEPCT>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_DESCRIPTION>' + dbo.fn_FormatXMLChars(cast(ISNULL(CI.Description,'') as nvarchar(max))) + '</OL.CI_DESCRIPTION>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_GENERALNOTES>' + dbo.fn_FormatXMLChars(cast(ISNULL(CI.GeneralNotes,'') as nvarchar(max))) + '</OL.CI_GENERALNOTES>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_MFGITEMNBR>' + dbo.fn_FormatXMLChars(case when OL.CatalogItemID > 0 then isnull(replace(CI.MFGItemNbr,'_',''),'') else isnull(OL.MFGItemNbr,'') end) + '</OL.CI_MFGITEMNBR>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_MKTDESCRIPTION>' + dbo.fn_FormatXMLChars(cast(ISNULL(MCI.MktDescription,'') as nvarchar(max))) + '</OL.CI_MKTDESCRIPTION>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_MKTFEATURES>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(MCI.MktFeatures,'') as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(MCI.MktFeatures,'') as nvarchar(max)),3,len(cast(ISNULL(MCI.MktFeatures,'') as nvarchar(max)))-2) else cast(ISNULL(MCI.MktFeatures,'') as nvarchar(max)) end,'-/',char(13)) ) + '</OL.CI_MKTFEATURES>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_MKTHIGHLIGHTS>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(MCI.MktHighlights,'') as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(MCI.MktHighlights,'') as nvarchar(max)),3,len(cast(ISNULL(MCI.MktHighlights,'') as nvarchar(max)))-2) else cast(ISNULL(MCI.MktHighlights,'') as nvarchar(max)) end,'-/',char(13)) ) + '</OL.CI_MKTHIGHLIGHTS>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_MKTOPTIONS1>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(MCI.MktOptions1,'') as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(MCI.MktOptions1,'') as nvarchar(max)),3,len(cast(ISNULL(MCI.MktOptions1,'') as nvarchar(max)))-2) else cast(ISNULL(MCI.MktOptions1,'') as nvarchar(max)) end,'-/',char(13)) ) + '</OL.CI_MKTOPTIONS1>'"
              mstrSQL = mstrSQL & "        + '<OL.CI_MKTOPTIONS2>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(MCI.MktOptions2,'') as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(MCI.MktOptions2,'') as nvarchar(max)),3,len(cast(ISNULL(MCI.MktOptions2,'') as nvarchar(max)))-2) else cast(ISNULL(MCI.MktOptions2,'') as nvarchar(max)) end,'-/',char(13)) ) + '</OL.CI_MKTOPTIONS2>'"
              mstrSQL = mstrSQL & "        + '<OL.MKTDESCRIPTION>' + dbo.fn_FormatXMLChars(cast(ISNULL(nullif(CI.MktDescription,''),ISNULL(MCI.MktDescription,'')) as nvarchar(max))) + '</OL.MKTDESCRIPTION>'"
              mstrSQL = mstrSQL & "        + '<OL.MKTFEATURES>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(nullif(CI.MktFeatures,''),ISNULL(MCI.MktFeatures,'')) as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(nullif(CI.MktFeatures,''),ISNULL(MCI.MktFeatures,'')) as nvarchar(max)),3,len(cast(ISNULL(nullif(CI.MktFeatures,''),ISNULL(MCI.MktFeatures,'')) as nvarchar(max)))-2) else cast(ISNULL(nullif(CI.MktFeatures,''),ISNULL(MCI.MktFeatures,'')) as nvarchar(max)) end,'-/',char(13)) ) + '</OL.MKTFEATURES>'"
              mstrSQL = mstrSQL & "        + '<OL.MKTHIGHLIGHTS>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(nullif(CI.MktHighlights,''),ISNULL(MCI.MktHighlights,'')) as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(nullif(CI.MktHighlights,''),ISNULL(MCI.MktHighlights,'')) as nvarchar(max)),3,len(cast(ISNULL(nullif(CI.MktHighlights,''),ISNULL(MCI.MktHighlights,'')) as nvarchar(max)))-2) else cast(ISNULL(nullif(CI.MktHighlights,''),ISNULL(MCI.MktHighlights,'')) as nvarchar(max)) end,'-/',char(13)) ) + '</OL.MKTHIGHLIGHTS>'"
              mstrSQL = mstrSQL & "        + '<OL.MKTOPTIONS1>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(nullif(CI.MktOptions1,''),ISNULL(MCI.MktOptions1,'')) as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(nullif(CI.MktOptions1,''),ISNULL(MCI.MktOptions1,'')) as nvarchar(max)),3,len(cast(ISNULL(nullif(CI.MktOptions1,''),ISNULL(MCI.MktOptions1,'')) as nvarchar(max)))-2) else cast(ISNULL(nullif(CI.MktOptions1,''),ISNULL(MCI.MktOptions1,'')) as nvarchar(max)) end,'-/',char(13)) ) + '</OL.MKTOPTIONS1>'"
              mstrSQL = mstrSQL & "        + '<OL.MKTOPTIONS2>' + dbo.fn_FormatXMLChars(replace(case when substring(cast(ISNULL(nullif(CI.MktOptions2,''),ISNULL(MCI.MktOptions2,'')) as nvarchar(max)),1,2) = '-/' then substring(cast(ISNULL(nullif(CI.MktOptions2,''),ISNULL(MCI.MktOptions2,'')) as nvarchar(max)),3,len(cast(ISNULL(nullif(CI.MktOptions2,''),ISNULL(MCI.MktOptions2,'')) as nvarchar(max)))-2) else cast(ISNULL(nullif(CI.MktOptions2,''),ISNULL(MCI.MktOptions2,'')) as nvarchar(max)) end,'-/',char(13)) ) + '</OL.MKTOPTIONS2>'"
              mstrSQL = mstrSQL & "        + '<OL.CSMP>' + dbo.fn_FormatCurrency(OL.SRCommCSMPCreditValue) + '</OL.CSMP>'"
              mstrSQL = mstrSQL & "        + '<OL.CSMPAMTALL>' + dbo.fn_FormatCurrency(ISNULL(OL.SRCommCSMPCreditValue,0) + ISNULL(OL.CSMPPCTAmt,0)) + '</OL.CSMPAMTALL>'"
              mstrSQL = mstrSQL & "        + '<OL.DEALERCOST>' + dbo.fn_FormatCurrency(ISNULL(OL.DealerCostAmt,0)) + '</OL.DEALERCOST>'"
              mstrSQL = mstrSQL & "        + '<OL.EXTMSRP>' + dbo.fn_FormatCurrency(ISNULL(CI.MFGPrice,0) * OL.Quantity) + '</OL.EXTMSRP>'"
              mstrSQL = mstrSQL & "        + '<OL.LINETOTAL>' + dbo.fn_FormatCurrency(OL.LineTotal) + '</OL.LINETOTAL>'"
              mstrSQL = mstrSQL & "        + '<OL.GFCLINETOTAL>' + case when OL.isPrimaryInd = -1 then dbo.fn_FormatCurrency(dbo.fn_GetMergedSellPrice(OL.OrderID, OL.BundleID)) else '' end + '</OL.GFCLINETOTAL>'"
              mstrSQL = mstrSQL & "        + '<OL.LINETOTAL24MOPYMT>' + dbo.fn_FormatCurrency(OL.LineTotal * OD.Lease24moFactor) + '</OL.LINETOTAL24MOPYMT>'"
              mstrSQL = mstrSQL & "        + '<OL.LINETOTAL36MOPYMT>' + dbo.fn_FormatCurrency(OL.LineTotal * OD.Lease36moFactor) + '</OL.LINETOTAL36MOPYMT>'"
              mstrSQL = mstrSQL & "        + '<OL.LINETOTAL48MOPYMT>' + dbo.fn_FormatCurrency(OL.LineTotal * OD.Lease48moFactor) + '</OL.LINETOTAL48MOPYMT>'"
              mstrSQL = mstrSQL & "        + '<OL.LINETOTAL60MOPYMT>' + dbo.fn_FormatCurrency(OL.LineTotal * OD.Lease60moFactor) + '</OL.LINETOTAL60MOPYMT>'"
              mstrSQL = mstrSQL & "        + '<OL.LINETOTALLEASEPYMT>' + dbo.fn_FormatCurrency(OL.LineTotal * OD.LeaseFactor) + '</OL.LINETOTALLEASEPYMT>'"
              mstrSQL = mstrSQL & "        + '<OL.MANUALENTRYFLAG>' + case when OL.CatalogItemID <=-100 then '*' else '' end + '</OL.MANUALENTRYFLAG>'"
              mstrSQL = mstrSQL & "        + '<OL.MFG>' + case when ISNULL(MFG.ProductMfgID, -1) > 0 then dbo.fn_FormatXMLChars(ISNULL(MFG.Name,'')) else ISNULL(OL.MFGName, '') end + '</OL.MFG>'"
              mstrSQL = mstrSQL & "        + '<OL.DESCRIPTION>' + dbo.fn_FormatXMLChars(cast(ISNULL(OL.Description,'') as nvarchar(max))) + '</OL.DESCRIPTION>'"
              mstrSQL = mstrSQL & "        + '<OL.DESCRIPTIONREL>' "
              mstrSQL = mstrSQL & "        + case when isnull(ol.usedequipmentid,-1) > 0   "
              mstrSQL = mstrSQL & "                 then "
              mstrSQL = mstrSQL & "                   dbo.fn_ReplaceHTMLChars(ue.machine) "
              mstrSQL = mstrSQL & "               else "
              mstrSQL = mstrSQL & "                   dbo.fn_FormatXMLChars(cast(ISNULL(OL.Description,'') as nvarchar(max))) "
              mstrSQL = mstrSQL & "          end "
              mstrSQL = mstrSQL & "          + '</OL.DESCRIPTIONREL>'"
              mstrSQL = mstrSQL & "        + '<OL.MODEL>' + dbo.fn_FormatXMLChars(ISNULL(OL.Model,'')) + '</OL.MODEL>'"
              mstrSQL = mstrSQL & "        + '<OL.MODEL-DESCRIPTION>' "
              mstrSQL = mstrSQL & "            + case when isnull(OL.UsedEquipmentID,-1) > -1 OR BPOL.UsedEquipmentID > 1"
              mstrSQL = mstrSQL & "                   then"
              mstrSQL = mstrSQL & "                         case when isnull(OL.UsedEquipmentID,-1) > -1 "
              mstrSQL = mstrSQL & "                                 then isnull(ea.Description, 'Unknown') "
              mstrSQL = mstrSQL & "                              else isnull(cast(OL.Description as nvarchar(max)), 'Unknown') "
              mstrSQL = mstrSQL & "                         end + isnull(' (' + EA.AssetTag + ')', '') "
              mstrSQL = mstrSQL & "                   else "
              mstrSQL = mstrSQL & "                      dbo.fn_FormatXMLChars(case when OL.CatalogItemID <= -100 "
              mstrSQL = mstrSQL & "                                            then case when (OL.Model = cast(OL.Description as nvarchar(max)) "
              mstrSQL = mstrSQL & "                                                            and cast(OL.Description as nvarchar(max))  <> '') "
              mstrSQL = mstrSQL & "                                                           OR (cast(OL.Description as nvarchar(max))  <> '' "
              mstrSQL = mstrSQL & "                                                               and OL.Model = '') "
              mstrSQL = mstrSQL & "                                                         then ISNULL(cast(OL.Description as nvarchar(max)),'') "
              mstrSQL = mstrSQL & "                                                      else "
              mstrSQL = mstrSQL & "                                                         case when (cast(OL.Description as nvarchar(max))  = '' and OL.Model <> '') "
              mstrSQL = mstrSQL & "                                                                   OR (CHARINDEX(OL.Model,cast(OL.Description as nvarchar(max)) ) > 0)  "
              mstrSQL = mstrSQL & "                                                                then ISNULL(OL.Model,'') "
              mstrSQL = mstrSQL & "                                                              else"
              mstrSQL = mstrSQL & "                                                                 ISNULL(OL.Model,'') + '-' + ISNULL(cast(OL.Description as nvarchar(max)),'') "
              mstrSQL = mstrSQL & "                                                         end "
              mstrSQL = mstrSQL & "                                                  end"
              mstrSQL = mstrSQL & "                                           Else"
              mstrSQL = mstrSQL & "                                             case when (CI.Model = cast(CI.Description as nvarchar(max)) and cast(CI.Description as nvarchar(max))  <> '') "
              mstrSQL = mstrSQL & "                                                       OR (cast(CI.Description as nvarchar(max))  <> '' and CI.Model = '') "
              mstrSQL = mstrSQL & "                                                    then ISNULL(cast(CI.Description as nvarchar(max)),'') "
              mstrSQL = mstrSQL & "                                                  else"
              mstrSQL = mstrSQL & "                                                     case when (cast(CI.Description as nvarchar(max))  = '' and CI.Model <> '') "
              mstrSQL = mstrSQL & "                                                               OR (CHARINDEX(CI.Model,cast(CI.Description as nvarchar(max)) ) > 0)  "
              mstrSQL = mstrSQL & "                                                            then ISNULL(CI.Model,'') "
              mstrSQL = mstrSQL & "                                                          else"
              mstrSQL = mstrSQL & "                                                             ISNULL(CI.Model,'') + '-' + ISNULL(cast(CI.Description as nvarchar(max)),'') "
              mstrSQL = mstrSQL & "                                                      end "
              mstrSQL = mstrSQL & "                                             end"
              mstrSQL = mstrSQL & "                                          End) "
              mstrSQL = mstrSQL & "             end + '</OL.MODEL-DESCRIPTION>'"
              mstrSQL = mstrSQL & "        + '<OL.MSRP>' + dbo.fn_FormatCurrency(ISNULL(OL.MSRP,0)) + '</OL.MSRP>'"
              mstrSQL = mstrSQL & "        + '<OL.NETDEALERCOST>' + case when ISNULL(OD.SRCommCSMPLevelID,-1) = -101 then dbo.fn_FormatCurrency(OL.AdjDealerCostAmt) else dbo.fn_FormatCurrency(OL.DealerCostAmt - OL.SRCommCSMPCreditValue) end + '</OL.NETDEALERCOST>'"
              mstrSQL = mstrSQL & "        + '<OL.NETREPCOST>' + case when ISNULL(OD.SRCommCSMPLevelID,-1) = -101 then dbo.fn_FormatCurrency(OL.AdjDealerCostAmt) else dbo.fn_FormatCurrency(OL.BuyPrice - OL.SRCommCSMPCreditValue) end + '</OL.NETREPCOST>'"
              mstrSQL = mstrSQL & "        + '<OL.PERBUNDLEQTY>' + cast(OL.PerBundleQuantity as nvarchar) + '</OL.PERBUNDLEQTY>'"
              mstrSQL = mstrSQL & "        + '<OL.PERCENTOVERBASE>' +  dbo.fn_formatnumber(case when (select sum(case when o.CatalogItemID < 0 then o.BuyPrice * o.Quantity else cp.BuyPrice * o.Quantity end) from SNOrderLine o with (nolock) left join SNCatalogPrice cp with (nolock) on cp.CatalogItemID = o.CatalogItemID left join SNPriceLevel PL with (nolock) on PL.PriceLevelID = CP.PriceLevelID where o.OrderID = OL.OrderID and isnull(PL.IsStandardInd,-1) <> 0) > 0"
              mstrSQL = mstrSQL & "                 then (OD.BoardCreditAmt - (select sum(case when o.CatalogItemID < 0 then o.BuyPrice * o.Quantity else cp.BuyPrice * o.Quantity end) from SNOrderLine o with (nolock) left join SNCatalogPrice cp with (nolock) on cp.CatalogItemID = o.CatalogItemID left join SNPriceLevel PL with (nolock) on PL.PriceLevelID = CP.PriceLevelID where o.OrderID = OL.OrderID and isnull(PL.IsStandardInd,-1) <> 0)) / (select sum(case when o.CatalogItemID < 0 then o.BuyPrice * o.Quantity else cp.BuyPrice * o.Quantity end) from SNOrderLine o with (nolock) left join SNCatalogPrice cp with (nolock) on cp.CatalogItemID = o.CatalogItemID left join SNPriceLevel PL with (nolock) on PL.PriceLevelID = CP.PriceLevelID where o.OrderID = OL.OrderID and isnull(PL.IsStandardInd,-1) <> 0)"
              mstrSQL = mstrSQL & "                 else 0 end * 100,2) + '%' + + '</OL.PERCENTOVERBASE>'"
              mstrSQL = mstrSQL & "        + '<OL.PRICELEVEL>' + dbo.fn_FormatXMLChars(case when OL.PriceLevelID > 0 or OL.Quantity = 0 then (select PL.Name from SNPriceLevel PL with (nolock) where PL.PriceLevelID = OL.PriceLevelID) else 'N/A' end) + '</OL.PRICELEVEL>'"
              mstrSQL = mstrSQL & "        + '<OL.QTY>' +  cast(OL.Quantity as nvarchar) + + '</OL.QTY>'"
              mstrSQL = mstrSQL & "        + '<OL.REVENUEABOVEBASE>' + dbo.fn_FormatCurrency(OD.BoardCreditAmt - (select sum(case when o.CatalogItemID < 0 then o.BuyPrice * o.Quantity else cp.BuyPrice * o.Quantity end) from SNOrderLine o with (nolock) left join SNCatalogPrice cp with (nolock) on cp.CatalogItemID = o.CatalogItemID left join SNPriceLevel PL with (nolock) on PL.PriceLevelID = CP.PriceLevelID where o.OrderID = OL.OrderID and isnull(PL.IsStandardInd,-1) <> 0)) + '</OL.REVENUEABOVEBASE>'"
              mstrSQL = mstrSQL & "        + '<OL.STANDARDPRICE>' + dbo.fn_FormatCurrency(case when OL.CatalogItemID < 0 then OL.BuyPrice else (select CP.BuyPrice from SNCatalogPrice CP with (nolock) join SNPriceLevel PL with (nolock) on PL.PriceLevelID = CP.PriceLevelID and PL.IsStandardInd <> 0 where CP.CatalogItemID = OL.CatalogItemID) end) + '</OL.STANDARDPRICE>'"
              If Len(CStr(mRS("col"))) > 0 Then
                mstrSQL = mstrSQL & CStr(mRS("val"))
              End If
              mstrSQL = mstrSQL & "        + '<OL.TOTALDEALERCOST>' + dbo.fn_FormatCurrency(ISNULL(OL.DealerCostAmt,0) * OL.Quantity) + '</OL.TOTALDEALERCOST>'"
              mstrSQL = mstrSQL & "        + '<OL.TOTALSTANDARDBUY>' + dbo.fn_FormatCurrency((select sum(case when o.CatalogItemID < 0 then o.BuyPrice * o.Quantity else cp.BuyPrice * o.Quantity end) from SNOrderLine o with (nolock) left join SNCatalogPrice cp with (nolock) on cp.CatalogItemID = o.CatalogItemID left join SNPriceLevel PL with (nolock) on PL.PriceLevelID = CP.PriceLevelID where o.OrderID = OL.OrderID and isnull(PL.IsStandardInd,-1) <> 0)) + '</OL.TOTALSTANDARDBUY>'"
              mstrSQL = mstrSQL & "        + '<OL.UNITPRICE>' + dbo.fn_FormatCurrency(OL.SellPrice) + '</OL.UNITPRICE>'"
              mstrSQL = mstrSQL & "        + '<OL.UNITPRICELEASEPYMT>' + dbo.fn_FormatCurrency(OL.SellPrice * OD.LeaseFactor) + '</OL.UNITPRICELEASEPYMT>'"
              mstrSQL = mstrSQL & "        + '<OL.GFCUNITPRICE>' + case when OL.isPrimaryInd = -1 then dbo.fn_FormatCurrency(dbo.fn_GetMergedSellPrice(OL.OrderID, OL.BundleID)/OL.Quantity) else '' end + '</OL.GFCUNITPRICE>'"
              mstrSQL = mstrSQL & "        + '<OL.UNITPRICEA>' + dbo.fn_FormatCurrency(OL.SellPrice + (SELECT SUM(AdjAmount) FROM SNOrderLineAdjust with (nolock) WHERE OrderLineID = OL.OrderLineID)) + '</OL.UNITPRICEA>'"
              mstrSQL = mstrSQL & "        + '<OL.PRODUCTCODE>' + dbo.fn_FormatXMLChars(ISNULL(CI.OMDCode,'')) + '</OL.PRODUCTCODE>'"
              mstrSQL = mstrSQL & "        + '<OL.BUNDLENAME>' + dbo.fn_FormatXMLChars(cast(isnull(OL.BundleName, '') as nvarchar)) + '</OL.BUNDLENAME>'"
              mstrSQL = mstrSQL & "        + '<OL.USEDEQUIPMENTID>' + cast(isnull(UE.UsedEquipmentID, '') as nvarchar) + '</OL.USEDEQUIPMENTID>'"
              mstrSQL = mstrSQL & "        + '<OL.UECOMMENT>' + cast(isnull(UE.Comment, '') as nvarchar) + '</OL.UECOMMENT>'"
              mstrSQL = mstrSQL & "        + '<OL.UEASSETTAG>' + cast(isnull(UE.AssetTag, '') as nvarchar) + '</OL.UEASSETTAG>'"
              mstrSQL = mstrSQL & "        + '<OL.UECHECKEDOUT>' + cast(isnull(UEU.Abbreviation, '') as nvarchar) + '</OL.UECHECKEDOUT>'"
              mstrSQL = mstrSQL & "        + '<OL.UEMACHINE>' + cast(isnull(dbo.fn_ReplaceHTMLChars(UE.Machine), '') as nvarchar(max)) + '</OL.UEMACHINE>'"
              mstrSQL = mstrSQL & "        + '<OL.UEMETER>' + cast(isnull(dbo.fn_ReplaceHTMLChars(UE.Meter), '') as nvarchar(max)) + '</OL.UEMETER>'"
              mstrSQL = mstrSQL & "        + '<OL.UEMESSAGE>' + cast(isnull(UE.Message, '') as nvarchar) + '</OL.UEMESSAGE>'"
              mstrSQL = mstrSQL & "        + '<OL.UEDEALERCOST>' + dbo.fn_FormatCurrency(UE.DealerCost) + '</OL.UEDEALERCOST>'"
              mstrSQL = mstrSQL & "        + '<OL.UESELLPRICE>' + dbo.fn_FormatCurrency(UE.SellPrice) + '</OL.UESELLPRICE>'"
              mstrSQL = mstrSQL & "        + '<OL.UEDTEXPIRED>' + dbo.fn_FormatDate(UE.DTExpired,3,0,0) + '</OL.UEDTEXPIRED>'"
              mstrSQL = mstrSQL & "        + '<OL.UESERIALNBR>' + cast(isnull(UE.SerialNbr, '') as nvarchar) + '</OL.UESERIALNBR>'"
              mstrSQL = mstrSQL & "        + '<OL.UESTATUSNAME>' + cast(isnull(UES.Name, '') as nvarchar) + '</OL.UESTATUSNAME>'"
              mstrSQL = mstrSQL & "        + '</OL>'"
              mstrSQL = mstrSQL & " FROM SNOrderLine as OL with (nolock)"
              mstrSQL = mstrSQL & " JOIN SNOrder as OD with (nolock) on OD.OrderID = OL.OrderID"
              mstrSQL = mstrSQL & " LEFT JOIN SNCatalogItem as CI with (nolock) on CI.CatalogItemID = OL.CatalogItemID"
              mstrSQL = mstrSQL & " LEFT JOIN " & mstrCatalogServer & ".SCCatalogData.dbo.SCCat_CatalogItem as MCI with (nolock) on MCI.CatalogItemID = CI.MasterCatalogItemID"
              mstrSQL = mstrSQL & " LEFT JOIN SNProductMfg as MFG with (nolock) on MFG.ProductMfgID = CI.MfgID"
              mstrSQL = mstrSQL & " LEFT JOIN EAUsedEquipment as UE with (nolock) on UE.UsedEquipmentID = OL.UsedEquipmentID"
              mstrSQL = mstrSQL & " LEFT JOIN EAAssets as EA with (nolock) on EA.EAEquipmentID = UE.EAEquipmentID"
              mstrSQL = mstrSQL & " LEFT JOIN SNUser as UEU with (nolock) on UEU.UserID = UE.CheckedOutUserID"
              mstrSQL = mstrSQL & " LEFT JOIN SNUEStatus as UES with (nolock) on UES.UEStatusID = UE.UEStatusID"
              mstrSQL = mstrSQL & " LEFT JOIN SNAssocCatalogItem as AC with (nolock) on AC.CatalogItemID = OL.CatalogItemID and AC.ParentCatalogItemID = OL.BundleParentCatalogItemID"
              If Len(CStr(mRS("col"))) > 0 Then
                mstrSQL = mstrSQL & " LEFT JOIN (select * from (select ol.OrderLineId, 'PRICELEVEL' + cast(pl.PriceLevelID as nvarchar) tag, cp.BuyPrice BuyPrice"
                mstrSQL = mstrSQL & "                           from SNOrderLine ol with (nolock)"
                mstrSQL = mstrSQL & "                           left join SNPriceLevel pl with (nolock) on isnull(pl.IsStandardInd,0) = 0"
                mstrSQL = mstrSQL & "                           left join SNCatalogPrice cp with (nolock) on cp.CatalogItemID = ol.CatalogItemID and cp.PriceLevelID = pl.PriceLevelID"
                mstrSQL = mstrSQL & "                           where isnull(ol.ServiceInd,0) = 0 and ol.OrderID = " & clngObjectKey & ") d"
                mstrSQL = mstrSQL & "            pivot(max(BuyPrice) for tag in(" & CStr(mRS("col")) & ")) r) p on p.OrderLineId = OL.OrderLineId"
              End If
              mstrSQL = mstrSQL & " JOIN SNOrderLine BPOL on BPOL.OrderID = OD.OrderID and BPOL.BundleID = OL.BundleID and BPOL.BundleOrder = 1"
              mstrSQL = mstrSQL & " Where ISNULL(OL.ServiceInd,0) = 0 AND ISNULL(AC.IsStarterSupply,0) <> -1 AND OL.OrderID = " & clngObjectKey